#!/usr/bin/env python

import datetime
from mako.template import Template
import os
import sys
import yaml

def generateSimpleBlocks(outputDirectory):
    SimpleBlocksYaml = os.path.join(os.path.dirname(__file__), "SimpleBlocks.yaml")
    SimpleBlockFactoryTmplCpp = os.path.join(os.path.dirname(__file__), 'tmpl', 'SimpleBlockFactory.tmpl.cpp')

    yml = None
    with open(SimpleBlocksYaml) as f:
        yml = yaml.load(f.read())

    tmpl = None
    with open(SimpleBlockFactoryTmplCpp) as f:
        tmpl = f.read()

    assert(yml)
    assert(tmpl)

    prefix = """
///////////////////////////////////////////////////////////////////////////////
// This file was auto-generated by KFRBlocksGen.py on {0}
///////////////////////////////////////////////////////////////////////////////

#include "PothosKFRBlock.hpp"
#include "Utility.hpp"

#include <Pothos/Framework.hpp>

#include <complex>
#include <string>

""".format(datetime.datetime.now())

    rendered = "\n".join([Template(tmpl).render(yaml=yml[factory]) for factory in yml])

    output = prefix + rendered

    outputFilepath = os.path.join(outputDirectory, "AutogenSimpleBlocks.cpp")
    with open(outputFilepath, "w") as f:
        f.write(output)

if __name__ == "__main__":
    outputDir = sys.argv[1]
    generateSimpleBlocks(outputDir)
